api/urls.py
from django.urls import path
from .views import getUserInfoView, getInfoView, createTaskView, searchUsersView, getTasksView, getTaskData, \
    createEmployeeView

urlpatterns = [
    path('get-user-info/<str:user_id>', getUserInfoView),
    path('get-info', getInfoView),
    path('create-task', createTaskView),
    path('search-users', searchUsersView),
    path('get-tasks', getTasksView),
    path('get-task-data/<str:task_id>', getTaskData),
    path('create-employee', createEmployeeView)
]

config/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hrm.urls')),
    path('api/', include('api.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hrm/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.loginView, name='login'),
    path('console/', views.console, name='console'),
    path('add_employee', views.addEmployeeView, name='add_employee'),
    path('register/<str:token>', views.RegisterView.as_view(), name='register'),
    # path('employee', views.employeeView, name='employee'),
    path('employees/<str:pk>', views.employeeProfileView, name='employee_profile'),
    path('create_task', views.createTaskView, name='create_task'),
    path('edit_task/<str:pk>', views.editTaskView, name='edit_task'),
    path('logout', views.logoutView, name='logout'),
    path('task_info/<str:pk>', views.taskInfoView, name='task_info'),
    path('send_notification', views.sendNotificationView, name='send_notification'),
    path('tasks/', views.tasksView, name='tasks'),
    path('statistics', views.statisticsView, name='statistics'),
    path('change_position', views.changePosition, name='change_position'),
    path('add_section', views.addSectionView, name='add_section'),
    path('my_section', views.mySectionView, name='my_section'),
    path('view-task/<str:pk>', views.viewTaskView, name='view_task'),
    # path('edit-profile/', views.editProfileView, name='edit_profile')
    path('employee_profile_test/', TemplateView.as_view(template_name='hrm/tests/employee_profile.html')),
    path('settings/', views.settingsView, name='settings')
]

hrm/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid
from datetime import datetime, timedelta


class Section(models.Model):
    name = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.name


class Address(models.Model):
    home_number = models.IntegerField(null=True)
    street = models.CharField(max_length=200, null=True)
    state = models.CharField(max_length=200, null=True)
    city = models.CharField(max_length=200, null=True)
    zip_code = models.IntegerField(null=True)
    country = models.CharField(max_length=200, null=True)

    def __str__(self):
        return f"address({self.id})"


class Info(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    photo = models.ImageField(upload_to='images/', null=True, blank=True)
    salary = models.CharField(max_length=200, null=True, blank=True)
    phone = models.CharField(max_length=200, null=True, blank=True)
    about = models.TextField(max_length=500, null=True, blank=True)
    address = models.ForeignKey(Address, on_delete=models.SET_NULL, related_name='employees_by_address', null=True,
                                blank=True)
    section = models.ForeignKey(Section, on_delete=models.SET_NULL, null=True, blank=True,
                                related_name='employees_by_section')

    def __str__(self):
        return self.user.username


class GenLink(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    token = models.UUIDField(default=uuid.uuid4, unique=True)
    expiration_date = models.DateTimeField(null=True, default=datetime.today() + timedelta(days=3))
    used = models.BooleanField(default=False)

    def is_expired(self):
        today = datetime.today()
        if self.expiration_date:
            if self.expiration_date >= today:
                return False
            else:
                return True
        else:
            return True

    def __str__(self):
        try:
            return f"{self.user.username}/{self.id}/{'used' if self.used else 'not used'}/{'expired' if self.is_expired() else ''}"
        except Exception:
            return f"gen-link/{self.id}/{'used' if self.used else 'not used'}/{'expired' if self.is_expired() else ''}"


class Task(models.Model):
    STATUS = (
        ('new', 'new'),
        ('processing', 'processing'),
        ('done', 'done')
    )
    task_giver = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='tasks_by_me',
                                   blank=True)
    assigned_to = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='tasks_to_me')
    name = models.CharField(max_length=200, null=True)
    context = models.TextField(max_length=5000)
    status = models.CharField(max_length=200, choices=STATUS, null=True, blank=True, default='new')
    date_given = models.DateTimeField(auto_now_add=True, null=True)
    deadline = models.DateTimeField(null=True)
    note = models.TextField(max_length=200, null=True, blank=True)
    rate = models.FloatField(null=True, blank=True)
    is_private = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class Notification(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='sent_notifications')
    receiver = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='received_notifications')
    text = models.CharField(max_length=200, null=True)

    def __str__(self):
        return f"{self.text} :{self.id}"

hrm/views.py
# imports
from django.shortcuts import render, redirect, HttpResponse, get_object_or_404
from django.http import HttpResponseForbidden
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import Group
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponseGone, HttpResponseBadRequest
from django.views.generic import View

# my tools
from .decorators import redirect_if_authenticated, authenticated_required, allowed_users
from .my_tools import calculateProgresses
from .my_tools import in_groups
from .models import *

# filters and Forms
from .forms import CreateTaskForm, CreatePreUserForm, RegisterUserForm
from .filters import EmployeeFilter, TaskFilter

# built in tools
import datetime as dt


@redirect_if_authenticated
@authenticated_required
def home(request):
    return render(request, 'hrm/home.html')


class RegisterView(View):
    def get(self, request, *args, **kwargs):
        token_validator = self.validate_token(kwargs['token'])
        if token_validator == 'valid':
            return render(request, 'hrm/auth/register.html')
        else:
            return token_validator

    def post(self, request, *args, **kwargs):
        token_validator = self.validate_token(kwargs['token'], _return=True)

        if isinstance(token_validator, GenLink):
            gen_link = token_validator

            form = RegisterUserForm(instance=gen_link.user, data=request.POST)
            if form.is_valid():
                form.save()
                gen_link.used = True
                gen_link.save()
                return redirect('login')
            else:
                errors = form.errors.as_data()
                context = {
                    'form': form,
                }
                if 'first_name' in errors:
                    context['first_name_error'] = list(errors['first_name'][0])[0]
                if 'last_name' in errors:
                    context['last_name_error'] = list(errors['last_name'][0])[0]
                if 'username' in errors:
                    context['username_error'] = list(errors['username'][0])[0]
                if 'password2' in errors:
                    context['password_error'] = list(errors['password2'][0])[0]
                return render(request, 'hrm/auth/register.html', context=context)
        else:
            return token_validator

    def validate_token(self, token, _return=False):
        try:
            token = uuid.UUID(token)
        except ValueError:
            return HttpResponseBadRequest("Invalid link")

        gen_link: GenLink = get_object_or_404(GenLink, token=token)

        if not gen_link.used and not gen_link.is_expired():
            if _return:
                return gen_link
            else:
                return 'valid'
        else:
            return HttpResponseGone("This link is expired")


@redirect_if_authenticated
def loginView(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/')
        else:
            context = {'error': 'username or password is not correct!'}
            return render(request, 'hrm/auth/login.html', context)
    return render(request, 'hrm/auth/login.html')


@authenticated_required
@allowed_users(['Director'])
def console(request):
    return render(request, 'hrm/console.html')


@authenticated_required
@allowed_users(['Director', 'Manager'])
def addEmployeeView(request):
    if request.method == "POST":
        email = request.POST.get("email")
        if in_groups(request, ['Director']):
            section = Section.objects.get(id=request.POST.get("section_id"))
            if request.POST.get("as_manager") == "true":
                group = Group.objects.get(name='Manager')
            else:
                group = Group.objects.get(name='Employee')
        else:
            section = request.user.employee.section
            group = Group.objects.get(name='Employee')

        form = CreatePreUserForm(username=email, email=email, section=section, group=group)
        if form.is_created():
            messages.warning(request, 'Employee is created!')
            return redirect(request.POST.get("next"))
        else:
            messages.error(request, form.error_message)
            return redirect(request.POST.get("next"))


# @authenticated_required
# @allowed_users(['Employee', 'Manager'])
# def employeeView(request):
#     employee = request.user
#     notifications = employee.received_notifications.all()
#
#     tasks = employee.tasks_to_me.all()
#     tasks_count = tasks.count()
#     tasks_done_count = tasks.filter(status='done').count()
#
#     # filtering tasks
#     task_filter = TaskFilter(request.GET, queryset=tasks)
#     tasks = task_filter.qs
#
#     tasks = calcu(tasks)
#
#     context = {
#         'employee': employee,
#         'notifications': notifications,
#         'tasks': tasks,
#         'tasks_count': tasks_count,
#         'tasks_done_count': tasks_done_count,
#         'filter': task_filter,
#
#         # navbar properties
#         'home_active': 'active',
#     }
#
#
# pass


@authenticated_required
@allowed_users(['Manager', 'Director'])
def employeeProfileView(request, pk):
    # navbar properties
    sections = Section.objects.all()
    employee = get_object_or_404(User, id=pk)

    if not (employee.info.section == request.user.info.section or in_groups(request, ['Director'])):
        return HttpResponseForbidden('You are not authorised to see this page')

    tasks = employee.tasks_to_me.all()
    # filtering tasks
    task_filter = TaskFilter(request.GET, queryset=tasks)
    tasks = task_filter.qs

    tasks_count = tasks.count()
    tasks_done_count = tasks.filter(status='done').count()

    tasks = tasksProcessor(tasks)

    if request.method == "POST":
        if request.POST.get("post_status") == "sendMessage":
            Notification.objects.create(sender=request.user, receiver=employee, text=request.POST.get('message'))

    context = {
        'employee': employee,
        'tasks': tasks,
        'filter': task_filter,
        'tasks_count': tasks_count,
        'tasks_done_count': tasks_done_count,

        # navbar properties
        'sections': sections
    }
    return render(request, 'hrm/employee_profile.html', context)


@authenticated_required
@allowed_users(['Director', 'Manager'])
def createTaskView(request):
    if request.method == 'POST':
        print(request.POST)
        employee = get_object_or_404(User, id=request.POST.get('assigned_to'))

        if not ((employee.info.section == request.user.info.section and employee.groups.filter(
                name='Employee').exists()) or in_groups(request, ['Director'])):
            return HttpResponse('<h3>You are not authorized to see this page!')

        form = CreateTaskForm(request.POST)
        if form.is_valid():
            task = form.save(commit=False)
            task.status = 'new'
            task.task_giver = request.user
            task.save()
            messages.success(request, 'Task is created!')

        else:
            messages.error(request, 'Failed to create task. Invalid credentials!')

        if request.POST.get('next'):
            return redirect(request.POST.get('next'))
        else:
            return redirect('/')


@authenticated_required
@allowed_users(['Director', 'Manager'])
def editTaskView(request, pk):
    # navbar properties
    sections = Section.objects.all()

    try:
        task = Task.objects.get(id=pk)
    except ObjectDoesNotExist:
        return HttpResponse("<h3>404 not found</h3>")

    if request.user == task.task_giver.user:
        form = CreateTaskForm(instance=task)

        if request.method == "POST":
            if 'save' in request.POST:
                task_giver = task.task_giver
                note = task.note

                form = CreateTaskForm(request.POST, instance=task)
                if form.is_valid():
                    task = form.save()
                    task.note = note
                    task.task_giver = task_giver
                    task.save()
                    return redirect(request.GET.get('next'))
                else:
                    print(form.errors)
            if 'delete' in request.POST:
                task.delete()
                return redirect(request.GET.get('next'))

        context = {
            'form': form,

            # navbar properties
            'sections': sections,
        }
        return render(request, 'hrm/edit_task.html', context)
    else:
        return redirect('view_task', pk=pk)


@authenticated_required
@allowed_users(['Director', 'Manager'])
def viewTaskView(request, pk):
    # navbar properties
    sections = Section.objects.all()

    if request.method == 'POST':
        return redirect(request.GET.get('next'))
    try:
        task = Task.objects.get(id=pk)
    except ObjectDoesNotExist:
        return HttpResponse("<h3>404 not found</h3>")

    context = {
        'task': task,

        # navbar properties
        'sections': sections
    }
    return render(request, 'hrm/view_task.html', context)


@authenticated_required
def logoutView(request):
    logout(request)
    return redirect('login')


@authenticated_required
@allowed_users(['Manager', 'Employee'])
def taskInfoView(request, pk):
    try:
        task = Task.objects.get(id=pk)
    except ObjectDoesNotExist:

hrm/templates/hrm/modals/create_task_modal.html
{% load custom_tags %}
{% load static %}
<div class="modal fade" id="createTaskModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Create Task</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="id_create_task_form">
                <div class="modal-body">
                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                <label for="id_assigned_to_input">Assign to</label>
                                <p><input id="id_assigned_to_input" disabled="disabled" name="assigned_to" class="form-control"
                                           required=""></p>
                                <input type="hidden" id="id_assigned_to_id">
                            </div>
                        </div>
                        <div class="col">

                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                <label for="id_name">Task name</label>
                                <p><input type="text" name="name" class="form-control" maxlength="200" required=""
                                          id="id_name"></p>
                            </div>
                        </div>
                        <div class="col">
                            <div class="form-group">
                                <label for="id_deadline">DeadLine</label>
                                <p><input class="form-control" type="datetime-local" name="deadline" value="T"
                                          required="" id="id_deadline"></p>
                            </div>
                        </div>
                    </div>
                    <p>Context</p>
                    <p><textarea name="context" cols="40" rows="10" class="form-control" maxlength="5000" required=""
                                 id="id_context"></textarea></p>
                </div>
                <div class="modal-footer">
                    <div id="id_create_task_loader" class=""></div>
                    <div id="id_create_task_loader_text" class="d-none">Loading&#8230;</div>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" name="save" value="Create" class="btn btn-primary">Create Task</button>
                </div>
            </form>
        </div>
    </div>
</div>

hrm/templates/hrm/modals/employee_profile_modal.html
{% load static %}
<style>
    .profile-head {
        transform: translateY(5rem)
    }

    .cover {
        background-color: #0088CC;
        background-size: cover;
        background-repeat: no-repeat
    }

    .name{
        color: white;
    }


</style>

<div class="modal fade" id="employeeProfileModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content p-0 m-0">
            <div id="id_profile_view" class="">
                <input id="user_id" type="hidden" class="form-control">
                <div class="bg-white rounded overflow-hidden">
                    <div class="px-4 pt-0 pb-4 cover">
                        <div class="media align-items-end profile-head">
                            <div class="profile mr-3 pb-1"><img id="id_profile_picture"
                                                           src=""
                                                           alt="..." width="130" class="rounded mb-2 img-thumbnail border-primary">
                            </div>
                            <div class="media-body mb-5 text-dark">
                                <h4 class="mt-0 mb-0"><span id="id_first_name" class="name"></span> <span class="name" id="id_last_name"></span>
                                </h4>
                                <p class="mb-3"><span class="name" id="id_username"></span></p>
                            </div>
                        </div>
                    </div>
                    <div class="bg-light p-4 d-flex justify-content-end text-center align-items-center mt-1">
                        <button style="pointer-events: none;"
                                class="btn btn-outline-success px-1 py-0 ml-3 mt-4 mr-auto"><i
                                class="fas fa-user-tie"></i>
                            <span id="id_group">group_lorem</span>
                        </button>
                        <ul class="list-inline mb-0">
                            <li class="list-inline-item">
                                <h5 class="font-weight-bold mb-0 d-block"><span id="id_tasks_count"></span></h5><small
                                    class="text-muted">
                                Total Tasks</small>
                            </li>
                            <li class="list-inline-item">
                                <h5 class="font-weight-bold mb-0 d-block"><span id="id_tasks_done_count"></span></h5>
                                <small
                                        class="text-muted">
                                    Done</small>
                            </li>
                            <li class="list-inline-item">
                                <h5 class="font-weight-bold mb-0 d-block"><span id="id_rating">rating_lorem</span></h5>
                                <small
                                        class="text-muted">
                                    Rating</small>
                            </li>
                        </ul>
                    </div>
                    <div class="px-4 py-3">
                        <p class="mb-3">
                            <!--                            <button style="pointer-events: none;" class="btn btn-outline-success px-1 py-0"><i-->
                            <!--                                    class="fas fa-user-tie"></i>-->
                            <!--                                <span id="id_group">group_lorem</span>-->
                            <!--                            </button>-->
                            <a id="id_section_href" href="/section/"
                               class="btn btn-outline-primary px-1 py-0">
                                <i class="fas fa-users"></i>
                                <span id="id_section">section_lorem</span>
                            </a>
                        </p>
                        <div class="card mb-2">
                            <div class="card-header">
                                <h4>About</h4>
                            </div>
                            <div class="card-body">
                                <p>
                                    <span id="id_about">about_lorem</span>
                                </p>
                            </div>
                        </div>

                        <div class="card mb-2">
                            <div class="card-header">
                                <h4>Address</h4>
                            </div>
                            <div class="card-body">
                                <p>
                                    <span id="id_address">about_lorem</span>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <div id="id_profile_loader" class="d-none"></div>
                <div id="id_profile_loader_text" class="d-none">Loading&#8230;</div>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <a id="id_profile_go" class="btn btn-primary text-light">Profile</a>
            </div>
        </div>
    </div>
</div>

hrm/templates/hrm/modals/view_task_modal.html
{% load custom_tags %}
{% load static %}
<style>
    .profile-picture{
        width: 50px;
        height: 50px;
        border-radius: 50%;
    }
</style>
<div class="modal fade" id="viewTaskModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">View Task</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="id_view_task_modal">
                <div class="modal-body">
                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                <label for="id_assigned_to_input">Task Giver</label>
                                <div class="card" style="cursor: pointer;">
                                    <div class="card-body p-2">
                                        <div class="d-flex align-items-center">
                                            <div class="col-auto pl-0">
                                                <img id="id_task_giver_photo_img" class="profile-picture m-0" src="" alt="profile photo">
                                            </div>
                                            <div class="col pl-0">
                                                <h4 id="id_task_giver_name"></h4>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col">
                            <div class="form-group">
                                <label for="id_assigned_to_input">Assigned to</label>
                                <div class="card" style="cursor: pointer;">
                                    <div class="card-body p-2">
                                        <div class="d-flex align-items-center">
                                            <div class="col-auto pl-0">
                                                <img id="id_assigned_to_img" class="profile-picture m-0" src="" alt="profile photo">
                                            </div>
                                            <div class="col pl-0">
                                                <h4 id="id_assigned_to_name"></h4>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                <label for="id_task_name">Task name</label>
                                <p><input type="text" name="name" class="form-control" maxlength="200" required=""
                                          id="id_task_name"></p>
                            </div>
                        </div>
                        <div class="col">
                            <div class="form-group">
                                <label for="id_task_deadline">DeadLine</label>
                                <p><input class="form-control" type="datetime-local" name="deadline" value="T"
                                          required="" id="id_task_deadline"></p>
                            </div>
                        </div>
                    </div>
                    <p>Context</p>
                    <p><textarea name="context" cols="40" rows="10" class="form-control" maxlength="5000" required=""
                                 id="id_task_context"></textarea></p>
                </div>
                <div class="modal-footer">
                    <div id="id_create_task_loader" class=""></div>
                    <div id="id_create_task_loader_text" class="d-none">Loading&#8230;</div>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" name="save" value="Create" class="btn btn-primary">Create Task</button>
                </div>
            </form>
        </div>
    </div>
</div>