api/urls.py
from django.urls import path
from .views import getUserInfoView, getInfoView, createTaskView, searchUsersView, getTasksView, getTaskData, \
    createEmployeeView

urlpatterns = [
    path('get-user-info/<str:user_id>', getUserInfoView),
    path('get-info', getInfoView),
    path('create-task', createTaskView),
    path('search-users', searchUsersView),
    path('get-tasks', getTasksView),
    path('get-task-data/<str:task_id>', getTaskData),
    path('create-employee', createEmployeeView)
]

config/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hrm.urls')),
    path('api/', include('api.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hrm/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.loginView, name='login'),
    path('console/', views.console, name='console'),
    path('add_employee', views.addEmployeeView, name='add_employee'),
    path('register/<str:token>', views.RegisterView.as_view(), name='register'),
    # path('employee', views.employeeView, name='employee'),
    path('employees/<str:pk>', views.employeeProfileView, name='employee_profile'),
    path('create_task', views.createTaskView, name='create_task'),
    path('edit_task/<str:pk>', views.editTaskView, name='edit_task'),
    path('logout', views.logoutView, name='logout'),
    path('task_info/<str:pk>', views.taskInfoView, name='task_info'),
    path('send_notification', views.sendNotificationView, name='send_notification'),
    path('tasks/', views.tasksView, name='tasks'),
    path('statistics', views.statisticsView, name='statistics'),
    path('change_position', views.changePosition, name='change_position'),
    path('add_section', views.addSectionView, name='add_section'),
    path('my_section', views.mySectionView, name='my_section'),
    path('view-task/<str:pk>', views.viewTaskView, name='view_task'),
    # path('edit-profile/', views.editProfileView, name='edit_profile')
    path('employee_profile_test/', TemplateView.as_view(template_name='hrm/tests/employee_profile.html')),
    path('settings/', views.settingsView, name='settings')
]

hrm/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid
from datetime import datetime, timedelta


class Section(models.Model):
    name = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.name


class Address(models.Model):
    home_number = models.IntegerField(null=True)
    street = models.CharField(max_length=200, null=True)
    state = models.CharField(max_length=200, null=True)
    city = models.CharField(max_length=200, null=True)
    zip_code = models.IntegerField(null=True)
    country = models.CharField(max_length=200, null=True)

    def __str__(self):
        return f"address({self.id})"


class Info(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    photo = models.ImageField(upload_to='images/', null=True, blank=True)
    salary = models.CharField(max_length=200, null=True, blank=True)
    phone = models.CharField(max_length=200, null=True, blank=True)
    about = models.TextField(max_length=500, null=True, blank=True)
    address = models.ForeignKey(Address, on_delete=models.SET_NULL, related_name='employees_by_address', null=True,
                                blank=True)
    section = models.ForeignKey(Section, on_delete=models.SET_NULL, null=True, blank=True,
                                related_name='employees_by_section')

    def __str__(self):
        return self.user.username


class GenLink(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    token = models.UUIDField(default=uuid.uuid4, unique=True)
    expiration_date = models.DateTimeField(null=True, default=datetime.today() + timedelta(days=3))
    used = models.BooleanField(default=False)

    def is_expired(self):
        today = datetime.today()
        if self.expiration_date:
            if self.expiration_date >= today:
                return False
            else:
                return True
        else:
            return True

    def __str__(self):
        try:
            return f"{self.user.username}/{self.id}/{'used' if self.used else 'not used'}/{'expired' if self.is_expired() else ''}"
        except Exception:
            return f"gen-link/{self.id}/{'used' if self.used else 'not used'}/{'expired' if self.is_expired() else ''}"


class Task(models.Model):
    STATUS = (
        ('new', 'new'),
        ('processing', 'processing'),
        ('done', 'done')
    )
    task_giver = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='tasks_by_me',
                                   blank=True)
    assigned_to = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='tasks_to_me')
    name = models.CharField(max_length=200, null=True)
    context = models.TextField(max_length=5000)
    status = models.CharField(max_length=200, choices=STATUS, null=True, blank=True, default='new')
    date_given = models.DateTimeField(auto_now_add=True, null=True)
    deadline = models.DateTimeField(null=True)
    note = models.TextField(max_length=200, null=True, blank=True)
    rate = models.FloatField(null=True, blank=True)
    is_private = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class Notification(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='sent_notifications')
    receiver = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='received_notifications')
    text = models.CharField(max_length=200, null=True)

    def __str__(self):
        return f"{self.text} :{self.id}"

hrm/views.py
# imports
from django.shortcuts import render, redirect, HttpResponse, get_object_or_404
from django.http import HttpResponseForbidden
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import Group
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponseGone, HttpResponseBadRequest
from django.views.generic import View

# my tools
from .decorators import redirect_if_authenticated, authenticated_required, allowed_users
from .my_tools import calculateProgresses
from .my_tools import in_groups
from .models import *

# filters and Forms
from .forms import CreateTaskForm, CreatePreUserForm, RegisterUserForm
from .filters import EmployeeFilter, TaskFilter

# built in tools
import datetime as dt


@redirect_if_authenticated
@authenticated_required
def home(request):
    return render(request, 'hrm/home.html')


class RegisterView(View):
    def get(self, request, *args, **kwargs):
        token_validator = self.validate_token(kwargs['token'])
        if token_validator == 'valid':
            return render(request, 'hrm/auth/register.html')
        else:
            return token_validator

    def post(self, request, *args, **kwargs):
        token_validator = self.validate_token(kwargs['token'], _return=True)

        if isinstance(token_validator, GenLink):
            gen_link = token_validator

            form = RegisterUserForm(instance=gen_link.user, data=request.POST)
            if form.is_valid():
                form.save()
                gen_link.used = True
                gen_link.save()
                return redirect('login')
            else:
                errors = form.errors.as_data()
                context = {
                    'form': form,
                }
                if 'first_name' in errors:
                    context['first_name_error'] = list(errors['first_name'][0])[0]
                if 'last_name' in errors:
                    context['last_name_error'] = list(errors['last_name'][0])[0]
                if 'username' in errors:
                    context['username_error'] = list(errors['username'][0])[0]
                if 'password2' in errors:
                    context['password_error'] = list(errors['password2'][0])[0]
                return render(request, 'hrm/auth/register.html', context=context)
        else:
            return token_validator

    def validate_token(self, token, _return=False):
        try:
            token = uuid.UUID(token)
        except ValueError:
            return HttpResponseBadRequest("Invalid link")

        gen_link: GenLink = get_object_or_404(GenLink, token=token)

        if not gen_link.used and not gen_link.is_expired():
            if _return:
                return gen_link
            else:
                return 'valid'
        else:
            return HttpResponseGone("This link is expired")


@redirect_if_authenticated
def loginView(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/')
        else:
            context = {'error': 'username or password is not correct!'}
            return render(request, 'hrm/auth/login.html', context)
    return render(request, 'hrm/auth/login.html')


@authenticated_required
@allowed_users(['Director'])
def console(request):
    return render(request, 'hrm/console.html')


@authenticated_required
@allowed_users(['Director', 'Manager'])
def addEmployeeView(request):
    if request.method == "POST":
        email = request.POST.get("email")
        if in_groups(request, ['Director']):
            section = Section.objects.get(id=request.POST.get("section_id"))
            if request.POST.get("as_manager") == "true":
                group = Group.objects.get(name='Manager')
            else:
                group = Group.objects.get(name='Employee')
        else:
            section = request.user.employee.section
            group = Group.objects.get(name='Employee')

        form = CreatePreUserForm(username=email, email=email, section=section, group=group)
        if form.is_created():
            messages.warning(request, 'Employee is created!')
            return redirect(request.POST.get("next"))
        else:
            messages.error(request, form.error_message)
            return redirect(request.POST.get("next"))


# @authenticated_required
# @allowed_users(['Employee', 'Manager'])
# def employeeView(request):
#     employee = request.user
#     notifications = employee.received_notifications.all()
#
#     tasks = employee.tasks_to_me.all()
#     tasks_count = tasks.count()
#     tasks_done_count = tasks.filter(status='done').count()
#
#     # filtering tasks
#     task_filter = TaskFilter(request.GET, queryset=tasks)
#     tasks = task_filter.qs
#
#     tasks = calcu(tasks)
#
#     context = {
#         'employee': employee,
#         'notifications': notifications,
#         'tasks': tasks,
#         'tasks_count': tasks_count,
#         'tasks_done_count': tasks_done_count,
#         'filter': task_filter,
#
#         # navbar properties
#         'home_active': 'active',
#     }
#
#
# pass


@authenticated_required
@allowed_users(['Manager', 'Director'])
def employeeProfileView(request, pk):
    # navbar properties
    sections = Section.objects.all()
    employee = get_object_or_404(User, id=pk)

    if not (employee.info.section == request.user.info.section or in_groups(request, ['Director'])):
        return HttpResponseForbidden('You are not authorised to see this page')

    tasks = employee.tasks_to_me.all()
    # filtering tasks
    task_filter = TaskFilter(request.GET, queryset=tasks)
    tasks = task_filter.qs

    tasks_count = tasks.count()
    tasks_done_count = tasks.filter(status='done').count()

    tasks = tasksProcessor(tasks)

    if request.method == "POST":
        if request.POST.get("post_status") == "sendMessage":
            Notification.objects.create(sender=request.user, receiver=employee, text=request.POST.get('message'))

    context = {
        'employee': employee,
        'tasks': tasks,
        'filter': task_filter,
        'tasks_count': tasks_count,
        'tasks_done_count': tasks_done_count,

        # navbar properties
        'sections': sections
    }
    return render(request, 'hrm/employee_profile.html', context)


@authenticated_required
@allowed_users(['Director', 'Manager'])
def createTaskView(request):
    if request.method == 'POST':
        print(request.POST)
        employee = get_object_or_404(User, id=request.POST.get('assigned_to'))

        if not ((employee.info.section == request.user.info.section and employee.groups.filter(
                name='Employee').exists()) or in_groups(request, ['Director'])):
            return HttpResponse('<h3>You are not authorized to see this page!')

        form = CreateTaskForm(request.POST)
        if form.is_valid():
            task = form.save(commit=False)
            task.status = 'new'
            task.task_giver = request.user
            task.save()
            messages.success(request, 'Task is created!')

        else:
            messages.error(request, 'Failed to create task. Invalid credentials!')

        if request.POST.get('next'):
            return redirect(request.POST.get('next'))
        else:
            return redirect('/')


@authenticated_required
@allowed_users(['Director', 'Manager'])
def editTaskView(request, pk):
    # navbar properties
    sections = Section.objects.all()

    try:
        task = Task.objects.get(id=pk)
    except ObjectDoesNotExist:
        return HttpResponse("<h3>404 not found</h3>")

    if request.user == task.task_giver.user:
        form = CreateTaskForm(instance=task)

        if request.method == "POST":
            if 'save' in request.POST:
                task_giver = task.task_giver
                note = task.note

                form = CreateTaskForm(request.POST, instance=task)
                if form.is_valid():
                    task = form.save()
                    task.note = note
                    task.task_giver = task_giver
                    task.save()
                    return redirect(request.GET.get('next'))
                else:
                    print(form.errors)
            if 'delete' in request.POST:
                task.delete()
                return redirect(request.GET.get('next'))

        context = {
            'form': form,

            # navbar properties
            'sections': sections,
        }
        return render(request, 'hrm/edit_task.html', context)
    else:
        return redirect('view_task', pk=pk)


@authenticated_required
@allowed_users(['Director', 'Manager'])
def viewTaskView(request, pk):
    # navbar properties
    sections = Section.objects.all()

    if request.method == 'POST':
        return redirect(request.GET.get('next'))
    try:
        task = Task.objects.get(id=pk)
    except ObjectDoesNotExist:
        return HttpResponse("<h3>404 not found</h3>")

    context = {
        'task': task,

        # navbar properties
        'sections': sections
    }
    return render(request, 'hrm/view_task.html', context)


@authenticated_required
def logoutView(request):
    logout(request)
    return redirect('login')


@authenticated_required
@allowed_users(['Manager', 'Employee'])
def taskInfoView(request, pk):
    try:
        task = Task.objects.get(id=pk)
    except ObjectDoesNotExist:

hrm/templates/hrm/console.html
<!DOCTYPE html>
{% load custom_tags %}
{% load static %}
<html lang="en">
<head>
    <title>Console</title>
    {% include 'hrm/common_cdn/head.html' %}
    <link rel="stylesheet" type="text/css" href="{% static 'hrm/css/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'hrm/css/x_checkbox.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'hrm/css/loading_element.css' %}">
    <style href="{% static 'hrm/css/paginator.css' %}"></style>
</head>
<body>
{% include 'hrm/navbar.html' %}

<section id="id_body" style="display: none" class="pt-2">
    <div class="container w-auto">
        <div class="row g-4 ">
            <div class="col-lg-12">
                <div class="card card-body m-1 p-3 shadow-sm mb-3 bg-white rounded">
                    <div id="id_users_search_form" class="d-flex form justify-content-start align-items-center">

                        <div class="col-auto d-flex justify-content-start align-items-center rounded border"
                             title="highlight search result">
                            <i class="fas fa-highlighter pr-3"></i>
                            <input id="id_checkbox_highlight" type="checkbox" class="form-control-sm">
                        </div>
                        <div class="col-auto" title="search by position">
                            <div class="input-group d-flex align-items-center">
                                <div class="input-group-prepend col-auto pr-1 pt-2" title="except this position">
                                    <input id="id_checkbox_position_not" class="css-checkbox" type="checkbox"/>
                                    <label for="id_checkbox_position_not" class="css-label"></label>
                                </div>
                                <select id="id_position_select" class="form-control col-auto">
                                    <option value="all" selected>all positions</option>
                                </select>
                            </div>

                        </div>
                        <div class="col-auto pl-1" title="search by section">
                            <div class="input-group d-flex align-items-center">
                                <div class="input-group-prepend col-auto pr-1 pt-2" title="except this section">
                                    <input id="id_checkbox_section_not" class="css-checkbox" type="checkbox"/>
                                    <label for="id_checkbox_section_not" class="css-label"></label>
                                </div>
                                <select id="id_sections_select" class="form-control col-auto">
                                    <option value="all" selected>all sections</option>
                                </select>
                            </div>

                        </div>
                        <div class="col pl-1" title="search by name or leave empty to get all users">
                            <div class="input-group">
                                <input type="text" class="form-control" id="id_search_users_keyword"
                                       placeholder="search all in all sections" autocomplete="off">
                                <div class="input-group-append">
                                    <button id="id_users_search_button" name="search_user"
                                            class="btn btn-primary">
                                        Search
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card m-1 shadow-sm p-1 mb-5 bg-white rounded">
                    <div class="card-header"><h4>Users:</h4></div>
                    <div class="card-body p-0">
                        <table class="table table-sm table-striped" id="id_users_table">
                            <thead class="table-dark">
                            <tr class="d-flex">
                                <th class="col-2">First Name</th>
                                <th class="col-2">Last Name</th>
                                <th class="col-3">Username</th>
                                <th class="col-2">Section</th>
                                <th class="col-1">Position</th>
                                <th class="col-1 text-center">Add Task</th>
                                <th class="col-1 text-center">View</th>
                            </tr>
                            </thead>
                            <tbody id="id_users_table_tbody">

                            </tbody>
                        </table>
                    </div>
                    {% include 'hrm/tools/paginator.html' %}
                </div>
            </div>
        </div>
    </div>
</section>

{% include 'hrm/modals/create_task_modal.html' %}
{% include 'hrm/modals/employee_profile_modal.html' %}

{% include 'hrm/common_cdn/footer.html' %}

<!-- twbs pagination-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/twbs-pagination/1.4.1/jquery.twbsPagination.min.js"></script>
<!-- function declarations and initiating -->
<script src="{% static 'hrm/js/console/init.js' %}"></script>
<!-- user search and filter -->
<script src="{% static 'hrm/js/console/search_users.js' %}"></script>
<!-- twbs pagination init -->
<script src="{% static 'hrm/js/paginator.js' %}"></script>
<!-- used to fetch spesific user data to show in profile modal -->
<script src="{% static 'hrm/js/console/viewUser.js' %}"></script>
<!-- creating task functions -->
<script src="{% static 'hrm/js/console/create_task.js' %}"></script>

</body>
</html>


hrm/templates/hrm/edit_profile.html
{% extends 'hrm/main.html' %}

{% block content %}
{% load static %}
<div class="container">
	<form action="" method="post">
		<div class="row gutters">
			{% csrf_token %}
			<div class="col-xl-3 col-lg-3 col-md-12 col-sm-12 col-12">
				<div class="card h-100">
					<div class="card-body">
						<div class="account-settings">
							<div class="user-profile">
								<div class="user-avatar">
									<img src="{% static 'hrm/images/avatar.png' %}" alt="image here">
								</div>
								<h6 class="user-name">{{employee.first_name}}&nbsp{{employee.last_name}}</h6>
								<h6 class="user-email">{{employee.username}}</h6>
							</div>
							<div class="about">
								<h5>About</h5>
								<p><textarea name="about" id="id_about" maxlength="500" class="form-control" cols="25" rows="5" required>{{employee.about}}</textarea></p>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="col-xl-9 col-lg-9 col-md-12 col-sm-12 col-12">
				<div class="card h-100">
					<div class="card-body">
						<div class="row gutters">
							<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
								<h6 class="mb-2 text-primary">Personal Details</h6>
							</div>
							<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
								<div class="form-group">
									<label for="id_full_name">Full Name</label>
									<input name="full_name" type="text" class="form-control" id="id_full_name" placeholder="Enter full name" value="{{employee.first_name}} {{employee.last_name}}" required>
								</div>
							</div>
							<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
								<div class="form-group">
									<label for="id_username">Username</label>
									<input name="username" type="text" class="form-control" id="id_username" placeholder="Enter username" value="{{employee.username}}" required>
								</div>
							</div>
							<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
								<div class="form-group">
									<label for="id_email">Email</label>
									<input name="email" type="email" class="form-control" id="id_email" placeholder="Enter email address" value="{{employee.email}}" required>
								</div>
							</div>
							<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
								<div class="form-group">
									<label for="id_phone">Phone</label>
									<input name="phone" type="text" class="form-control" id="id_phone" placeholder="Enter phone number" value="{{employee.phone}}" required>
								</div>
							</div>
						</div>
						<div class="row gutters">
							<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
								<h6 class="mt-3 mb-2 text-primary">Address</h6>
							</div>
							<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
								<div class="form-group">
									<label for="id_street">Street</label>
									<input name="street" value="{{employee.address.street}}" type="text" class="form-control" id="id_street" placeholder="Enter Street" required>
								</div>
							</div>
							<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
								<div class="form-group">
									<label for="id_city">City</label>
									<input name="city" value="{{employee.address.city}}" type="text" class="form-control" id="id_city" placeholder="Enter City" required>
								</div>
							</div>
							<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
								<div class="form-group">
									<label for="id_state">State</label>
									<input name="state" value="{{employee.address.state}}" type="text" class="form-control" id="id_state" placeholder="Enter State" required>
								</div>
							</div>
							<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
								<div class="form-group">
									<label for="id_zip_code">Zip Code</label>
									<input name="zip_code" value="{{employee.address.zip_code}}" type="number" class="form-control" id="id_zip_code" placeholder="Zip Code" required>
								</div>
							</div>
						</div>
						<div class="row gutters">
							<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
								<div class="text-right">
									<button type="submit" value="submit" class="btn btn-primary">Update</button>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</form>

</div>

<style type="text/css">
body {
    margin: 0;
    color: #2e323c;
    background: #f5f6fa;
    position: relative;
    height: 100%;
}
.container {
	padding-top: 30px;
}
.account-settings .user-profile {
    margin: 0 0 1rem 0;
    padding-bottom: 1rem;
    text-align: center;
}
.account-settings .user-profile .user-avatar {
    margin: 0 0 1rem 0;
}
.account-settings .user-profile .user-avatar img {
    width: 90px;
    height: 90px;
    -webkit-border-radius: 100px;
    -moz-border-radius: 100px;
    border-radius: 100px;
}
.account-settings .user-profile h5.user-name {
    margin: 0 0 0.5rem 0;
}
.account-settings .user-profile h6.user-email {
    margin: 0;
    font-size: 0.8rem;
    font-weight: 400;
    color: #9fa8b9;
}
.account-settings .about {
    margin: 2rem 0 0 0;
    text-align: center;
}
.account-settings .about h5 {
    margin: 0 0 15px 0;
    color: #007ae1;
}
.account-settings .about p {
    font-size: 0.825rem;
}
.form-control {
    border: 1px solid #cfd1d8;
    -webkit-border-radius: 2px;
    -moz-border-radius: 2px;
    border-radius: 2px;
    font-size: .825rem;
    background: #ffffff;
    color: #2e323c;
}

.card {
    background: #ffffff;
    -webkit-border-radius: 5px;
    -moz-border-radius: 5px;
    border-radius: 5px;
    border: 0;
    margin-bottom: 1rem;
}


</style>

{% endblock %}

hrm/templates/hrm/task_info.html
{% extends 'hrm/main.html' %}

{% block content %}
<div class="row m-3">
    <div class="col">
        <form action="" method="POST">
            {% csrf_token %}
            <div class="card border-info mb-3" style="max-width: 100%;">
                <div class="card-header">
                    <h3>{{task.name}}</h3>
                    <p><i>task from <a href="{% url 'employee_profile' task.task_giver.id %}">{{task.task_giver}}</a></i></p>
                </div>
                <div class="card-body">
                    <h5 class="card-title text-info"><b>{{task.context}}</b></h5>
                    <br>
                    <p><b>Status:</b></p>
                    <p class="card-text">
                        <select name="status" class="form-control" style="max-width: 15%;" required="" id="id_status">
                            {% for key, value in select_options.items %}
                             <option value="{{key}}" {{value}}>{{key}}</option>
                            {% endfor %}
                        </select>
                    </p>
                    <p><b>Add note:</b></p>
                    <p><textarea style="max-width: 50%;"  name="note" cols="20" rows="3" maxlength="500" class="form-control" required="" id="id_note">{{task.note}}</textarea></p>
                    <div style="text-align: right;"><input type="submit" class="btn btn-info" value="Update" name="submit"></div>

                </div>
            </div>
        </form>
    </div>
</div>



{% endblock %}

hrm/templates/hrm/view_task.html
{% extends 'hrm/main.html' %}

{% block content %}
<div class="row m-5">
    <div class="col-md w-25">
        <div class="card p-5">
            <h3>View task</h3>
            <p><i>task from <a href="{% url 'employee_profile' task.task_giver.id %}">{{task.task_giver}}</a></i></p>
            <hr>
            <div class="row">
                <div class="col">
                    <div class="form-group">
                        <label>Assigned to</label>
                        <input type="text" value="{{task.assigned_to}}" class="form-control w-50" disabled>
                  </div>
                </div>
                <div class="col">
                    <div class="form-group">
                        <label>Task name</label>
                        <input type="text" value="{{task.name}}" class="form-control w-50" disabled>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="form-group">
                        <label>Status</label>
                        <input type="text" value="{{task.status}}" class="form-control w-50" disabled>
                  </div>
                </div>
                <div class="col">
                    <div class="form-group">
                        <label for="formGroupExampleInput">DeadLine</label>
                        <p><input class="form-control w-50" type="datetime-local" value="{{ task.deadline|date:'Y-m-d' }}T{{ task.deadline|date:'h:i:s' }}" disabled></p>
                    </div>
                </div>
            </div>
            <p>Context</p>

            <p><textarea name="context" cols="40" rows="5" class="form-control" maxlength="5000" required="" id="id_context" disabled>{{task.context}}</textarea></p>
            <div class="card">
                <div class="card-header">Note from the employee</div>
                <div class="card-body">
                    <i>{{task.note}}</i>
                </div>
            </div>
            <form action="" method="POST" style="text-align: right;">
                {% csrf_token %}
                <input type="submit" value="Back" class="btn btn-info mt-2"/>
            </form>
        </div>
    </div>
</div>

{% endblock %}